"""Nuke script (`.nk`) writer for camera tracks.

Emits a `Camera2` node with animated `focal`, `translate`, and `rotate`
knobs — Camera2 is supported back to Nuke 11 and renders identically to
Camera3 for our single-pinhole use case, so we favour it for broader
pipeline compatibility.

The sidecar lives next to the plate at
`<plate_folder>/camera_track/<shot>.camera.nk`. Compositors drop it into
their script via File → Import Script, or drag-and-drop, and get a ready-
to-use 3D camera animated over the plate's frame range.

Knob conventions we emit (locked so Nuke imports correctly):
- `rot_order ZXY`               — matches `CameraSolve.conventions.rot_order`
- `translate`                   — three curves (tx, ty, tz) in solve units
- `rotate`                      — three curves (rx, ry, rz) in degrees
- `focal`                       — single curve in mm
- `haperture` / `vaperture`     — single scalars (sensor dimensions in mm)
- `note` knob                   — solver provenance + scale caveat
"""

from __future__ import annotations

from live_action_aov.io.camera_schema import CameraSolve

_HEADER = (
    "# Generated by live-action-aov camera track — do not edit.\n"
    "# Drop into your comp via File → Import Script, or drag & drop.\n"
    "# Camera2 chosen for Nuke 11+ compatibility; swap to Camera3 manually if needed.\n\n"
)


def _curve_K(frame_value_pairs: list[tuple[int, float]]) -> str:
    """Render a Nuke animation curve expression.

    Nuke format: `{curve K x<frame> <value> x<frame> <value> ...}`. The
    leading `K` tags constant-interpolation between keyframes; switch to
    `L` for linear if the plate is sub-frame-accurate. We use K because
    the solve is keyed per frame — no need to interpolate.
    """
    if not frame_value_pairs:
        return "0"
    parts = [f"x{f} {v:.6f}" for f, v in frame_value_pairs]
    return "{curve K " + " ".join(parts) + "}"


def render_nuke_camera_script(solve: CameraSolve, *, node_name: str | None = None) -> str:
    """Serialize a `CameraSolve` into a Nuke `.nk` Camera2 node."""
    name = node_name or f"LiveActionAOV_Camera_{solve.shot.name or 'shot'}"

    # Animated curves, keyed off the solve's registered frames only.
    # Unregistered frames are omitted; Nuke's constant interpolation will
    # hold the prior value, which is the safer visual default than a
    # zero-reset jump. The unregistered list is surfaced in the JSON so
    # the user can decide whether to interpolate manually.
    focal_curve = [
        (e.frame, _focal_mm(solve.intrinsics, e.frame))
        for e in solve.extrinsics
    ]
    tx_curve = [(e.frame, e.translation[0]) for e in solve.extrinsics]
    ty_curve = [(e.frame, e.translation[1]) for e in solve.extrinsics]
    tz_curve = [(e.frame, e.translation[2]) for e in solve.extrinsics]
    rx_curve = [(e.frame, e.rotation_euler_zxy_deg[0]) for e in solve.extrinsics]
    ry_curve = [(e.frame, e.rotation_euler_zxy_deg[1]) for e in solve.extrinsics]
    rz_curve = [(e.frame, e.rotation_euler_zxy_deg[2]) for e in solve.extrinsics]

    note = (
        f"Solved by live-action-aov / {solve.backend.name} {solve.backend.version}.\\n"
        f"Axis: {solve.conventions.axis_system}, camera: {solve.conventions.camera_convention}.\\n"
        f"Units: {solve.conventions.units} — {solve.conventions.unit_note}\\n"
        f"Reprojection error (aggregate): "
        f"{solve.quality.aggregate_reprojection_error_px:.3f} px over "
        f"{solve.quality.registered_frame_count}/{solve.quality.total_frame_count} frames."
    )

    body = (
        "Camera2 {\n"
        " inputs 0\n"
        f" rot_order {solve.conventions.rot_order}\n"
        f" focal {_curve_K(focal_curve)}\n"
        f" haperture {solve.intrinsics.haperture_mm_hint:.6f}\n"
        f" vaperture {solve.intrinsics.vaperture_mm_hint:.6f}\n"
        " near 0.1\n"
        " far 10000\n"
        f" translate {{{_curve_K(tx_curve)} {_curve_K(ty_curve)} {_curve_K(tz_curve)}}}\n"
        f" rotate {{{_curve_K(rx_curve)} {_curve_K(ry_curve)} {_curve_K(rz_curve)}}}\n"
        f' note "{note}"\n'
        f" name {name}\n"
        "}\n"
    )

    return _HEADER + body


def _focal_mm(intrinsics, frame: int) -> float:
    """Focal in mm for Nuke, derived from fx_px + haperture_mm_hint.

    `focal_mm = fx_px * haperture_mm / width_px`. We don't vary focal per
    frame in v2a (COLMAP's SINGLE camera mode gives one intrinsics set
    for the whole clip) so `frame` is currently ignored — but the
    signature leaves the door open for animated focal from zoom solves
    (v2b).
    """
    del frame
    if intrinsics.focal_mm_hint is not None:
        return float(intrinsics.focal_mm_hint)
    return float(intrinsics.fx_px * intrinsics.haperture_mm_hint / max(intrinsics.width_px, 1))


__all__ = ["render_nuke_camera_script"]
