"""Shared test fixtures and runtime NoOpPass registration.

Registers the `NoOpPass` defined in `tests/support/noop_pass.py` into the
global PluginRegistry so end-to-end tests can exercise the full pipeline
without any real AI inference plugin installed (Phase 0 exit criterion).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from live_action_aov.core.registry import get_registry
from tests.support.noop_pass import NoOpPass


@pytest.fixture(scope="session", autouse=True)
def _register_noop_pass() -> None:
    """Register the test-only NoOpPass before any test runs."""
    get_registry().register_pass("noop", NoOpPass)


@pytest.fixture(scope="session")
def test_plate_1080p(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Generate a short synthetic 1080p EXR sequence.

    Session-scoped so all tests share one fixture. Smaller-resolution
    variants are generated by individual tests as needed.
    """
    from tests.fixtures.generate_test_plate import generate

    folder = tmp_path_factory.mktemp("test_plate_1080p")
    generate(folder, frame_count=5, width=640, height=360)
    return folder
