"""Text-template checks on the Nuke `.nk` writer.

We don't have a Nuke interpreter in CI, so these tests do structural
checks on the emitted script: the right node type, knobs wired up with
`{curve K ...}` expressions, conventions broadcast in the `note` knob,
and frame-value pairs appearing in the order the user expects.

Round-trip through Nuke itself is part of the manual QA, not CI.
"""

from __future__ import annotations

from live_action_aov.io.camera_schema import (
    BackendInfo,
    CameraSolve,
    Extrinsic,
    Intrinsics,
    Quality,
    ShotRef,
)
from live_action_aov.io.writers.nuke_script import render_nuke_camera_script


def _solve_two_frames() -> CameraSolve:
    return CameraSolve(
        shot=ShotRef(name="shot_42", frame_range=(1001, 1002), resolution=(1920, 1080)),
        backend=BackendInfo(name="pycolmap", version="4.0.3"),
        intrinsics=Intrinsics(
            fx_px=2100.0,
            fy_px=2100.0,
            cx_px=960.0,
            cy_px=540.0,
            width_px=1920,
            height_px=1080,
            haperture_mm_hint=24.892,
        ),
        extrinsics=[
            Extrinsic(
                frame=1001,
                translation=(1.0, 2.0, 3.0),
                rotation_euler_zxy_deg=(10.0, 20.0, 30.0),
                rotation_matrix=(
                    (1.0, 0.0, 0.0),
                    (0.0, 1.0, 0.0),
                    (0.0, 0.0, 1.0),
                ),
            ),
            Extrinsic(
                frame=1002,
                translation=(1.5, 2.5, 3.5),
                rotation_euler_zxy_deg=(11.0, 21.0, 31.0),
                rotation_matrix=(
                    (1.0, 0.0, 0.0),
                    (0.0, 1.0, 0.0),
                    (0.0, 0.0, 1.0),
                ),
            ),
        ],
        quality=Quality(
            aggregate_reprojection_error_px=0.42,
            registered_frame_count=2,
            total_frame_count=2,
        ),
    )


def test_script_starts_with_header_and_camera_node():
    out = render_nuke_camera_script(_solve_two_frames())
    assert out.startswith("# Generated by live-action-aov")
    assert "Camera2 {" in out
    assert out.rstrip().endswith("}")


def test_rot_order_matches_schema():
    out = render_nuke_camera_script(_solve_two_frames())
    assert "rot_order ZXY" in out


def test_focal_curve_uses_expected_mm_value():
    # focal_mm = fx_px * haperture_mm / width_px = 2100 * 24.892 / 1920 = 27.225625 mm
    out = render_nuke_camera_script(_solve_two_frames())
    # Both keyframes should use the same mm value (SINGLE camera mode in v2a)
    assert "focal {curve K x1001 27.225625 x1002 27.225625}" in out


def test_translate_emits_three_sub_curves_in_order():
    out = render_nuke_camera_script(_solve_two_frames())
    # Nuke multi-value knobs take N space-separated curve expressions.
    assert "translate {{curve K x1001 1.000000 x1002 1.500000}" in out
    assert " {curve K x1001 2.000000 x1002 2.500000}" in out
    assert " {curve K x1001 3.000000 x1002 3.500000}}" in out


def test_rotate_emits_degrees_as_numeric_values():
    out = render_nuke_camera_script(_solve_two_frames())
    assert "rotate {{curve K x1001 10.000000 x1002 11.000000}" in out
    assert " {curve K x1001 20.000000 x1002 21.000000}" in out
    assert " {curve K x1001 30.000000 x1002 31.000000}}" in out


def test_note_surfaces_solver_provenance():
    out = render_nuke_camera_script(_solve_two_frames())
    assert "Solved by live-action-aov / pycolmap 4.0.3" in out
    assert "y_up_rh" in out
    assert "unitless" in out
    assert "Reprojection error (aggregate): 0.420 px" in out


def test_named_node_honoured():
    out = render_nuke_camera_script(_solve_two_frames(), node_name="MyCustomCam")
    assert "name MyCustomCam\n" in out


def test_apertures_written_as_scalars_not_curves():
    out = render_nuke_camera_script(_solve_two_frames())
    # These knobs are constant over the clip — confirm no `curve K` wrap.
    assert "haperture 24.892000\n" in out
    assert "vaperture 18.669000\n" in out
